// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxxafnabhdmuottdgah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeHhhZm5hYmhkbXVvdHRkZ2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTc1OTgsImV4cCI6MjA2MTI3MzU5OH0.h5RDNqCKMMAjhtk87kDBOwpCaIpA3rKER-t0NxjE4f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);